### ISSUE TITLE
Unknown NPE error in 1.12.2

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#152]
[17:51:39 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'trg' in plugin TriggerReactor v2.1.4
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_191]
at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_191]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [1.12.2.jar:git-Spigot-e8ded36-acbc348]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at io.github.wysohn.triggerreactor.core.main.TriggerReactor.onCommand(TriggerReactor.java:198) ~[TriggerReactor%20(1).jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onCommand(TriggerReactor.java:71) ~[TriggerReactor%20(1).jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[1.12.2.jar:git-Spigot-e8ded36-acbc348]

**Comment by wysohn** [comment]
This is outdated version
