### ISSUE TITLE
Plugin does not start. NullPointerException

### ISSUE THREAD

**Issue by Noxillio** [wysohn/TriggerReactor#202]
```
[07:14:44 ERROR]: Error occurred while enabling TriggerReactor v2.2.0 (Is it up to date?)
java.lang.NullPointerException: null
at io.github.wysohn.triggerreactor.bukkit.manager.ExecutorManager.reload(ExecutorManager.java:62) ~[?:?]
at io.github.wysohn.triggerreactor.bukkit.manager.ExecutorManager.<init>(ExecutorManager.java:49) ~[?:?]
at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onEnable(JavaPluginBridge.java:216) ~[?:?]
at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:57) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-176]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-176]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-176]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-176]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870) ~[patched_1.14.4.jar:git-Paper-176]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

Same error after updating Paper from 176 to 192.

**Comment by gerzytet** [comment]
Fixed in release 2.2.0
