### ISSUE TITLE
ArrayIndexOutOfBound for LocationBasedTrigger

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#219]
Probably related to #145

> [20:27:38] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: 1
[20:27:38] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractLocationBasedTriggerManager.stringToSloc(AbstractLocationBasedTriggerManager.java:152)
[20:27:38] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractLocationBasedTriggerManager.loadTriggers(AbstractLocationBasedTriggerManager.java:64)
[20:27:38] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractLocationBasedTriggerManager.reload(AbstractLocationBasedTriggerManager.java:47)
[20:27:38] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onEnable(JavaPluginBridge.java:252)
[20:27:38] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:57)
[20:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[20:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338)
[20:27:38] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420)
[20:27:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467)
[20:27:38] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381)
[20:27:38] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474)
[20:27:38] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290)
[20:27:38] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:870)
[20:27:38] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by gerzytet** [comment]
@wysohn 
can you give reproduction steps so I can confirm whether or not this happens in an official release?

**Comment by wysohn** [comment]
@gerzytet 
It's in Beta

The person who reported it somehow left the discord channel, so I have no idea how it happened

**Comment by rkdrns4747** [comment]
solved in 36c1450
