### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by Poseidon23** [wysohn/TriggerReactor#31]
/trg custom onInteract test #MESSAGE +player.getName()
`
[19:29:52] [Server thread/WARN]: io.github.wysohn.triggerreactor.core.manager.trigger.AbstractTriggerManager$TriggerInitFailedException: Failed to initialize Trigger [CustomTrigger -- test]!
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractTriggerManager$Trigger.init(AbstractTriggerManager.java:107)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractCustomTriggerManager$CustomTrigger.<init>(AbstractCustomTriggerManager.java:42)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractCustomTriggerManager.createCustomTrigger(AbstractCustomTriggerManager.java:130)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.main.TriggerReactor.onCommand(TriggerReactor.java:745)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onCommand(TriggerReactor.java:71)
[19:29:52] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[19:29:52] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[19:29:52] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[19:29:52] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[19:29:52] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[19:29:52] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[19:29:52] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:29:52] [Server thread/WARN]: Caused by: io.github.wysohn.triggerreactor.core.script.parser.ParserException: Unexpected token [type: OPERATOR_A, value: '+'] near row: 1, col:12
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parseFactor(Parser.java:554)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parseTerm(Parser.java:431)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parseExpression(Parser.java:389)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parseComparison(Parser.java:362)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parseLogic(Parser.java:320)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parseStatement(Parser.java:204)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.script.parser.Parser.parse(Parser.java:61)
[19:29:52] [Server thread/WARN]: 	at io.github.wysohn.triggerreactor.core.manager.trigger.AbstractTriggerManager$Trigger.init(AbstractTriggerManager.java:103)
[19:29:52] [Server thread/WARN]: 	... 20 more
`

**Comment by wysohn** [comment]
Ok l, I know you are frustrated, but obviously it already gave you the reason why it's not working.

[19:29:52] [Server thread/WARN]: Caused by: io.github.wysohn.triggerreactor.core.script.parser.ParserException: Unexpected token [type: OPERATOR_A, value: '+'] near row: 1, col:12

You are using + operator out of the blue, and TriggerReactor don't understand what you are trying to do.

Adding what to what? Everything is logic, so carefully think about it.

As a hint, you can add numbers like 1 + 2 or append string like "hello "+"world"
