### ISSUE TITLE
I Can't use This Plugin on my bukkit.

### ISSUE THREAD

**Issue by StayCake** [wysohn/TriggerReactor#57]
Error occurred while enabling TriggerReactor v1.4.1 (Is it up to date?)
java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
        at io.github.wysohn.triggerreactor.tools.ReflectionUtil.getAllClasses(ReflectionUtil.java:347) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.manager.trigger.CustomTriggerManager.initEvents(CustomTriggerManager.java:89) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.manager.trigger.CustomTriggerManager.<init>(CustomTriggerManager.java:74) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onEnable(JavaPluginBridge.java:269) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:58) ~[TriggerReactor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[Paper.jar:git-Paper-1322]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [Paper.jar:git-Paper-1322]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Paper.jar:git-Paper-1322]
        at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366) [PlugMan.jar:?]
        at com.rylinaux.plugman.command.LoadCommand.execute(LoadCommand.java:114) [PlugMan.jar:?]
        at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95) [PlugMan.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Paper.jar:git-Paper-1322]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) [Paper.jar:git-Paper-1322]
        at gyurix.commands.CustomCommandMap.dispatch(CustomCommandMap.java:89) [SpigotLib.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:677) [Paper.jar:git-Paper-1322]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:640) [Paper.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:464) [Paper.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [Paper.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [Paper.jar:git-Paper-1322]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [Paper.jar:git-Paper-1322]
        at java.lang.Thread.run(Unknown Source) [?:?]

What is this error?
I'm using 1.12.2 Paper Bukkit.

I just tried restart, load it plugin managers too.
But it doesn't loaded.

**Comment by wysohn** [comment]
It seems to be you are using Java9, but I recommend you to use Java8 instead as Java9 is still new. I'm not planning to jump into Java9 yet. Do you have any specific reason to move to Java9 already?
