### ISSUE TITLE
Not compatible with FactionUUID 1.6.9.5

### ISSUE THREAD

**Issue by Ghost295** [wysohn/TriggerReactor#63]
Any trg commands return null with FactionUUID installed on the 1.8.8 spigot server without it, the plugin works:

With the last dev build:

`[21:58:49 INFO]: [TriggerReactor] Enabling TriggerReactor v1.4.3
[21:58:49 INFO]: [TriggerReactor] Enabled support for ProtocolLib ProtocolLib v4.3.0
[21:58:49 INFO]: [TriggerReactor] Enabled support for PlaceholderAPI PlaceholderAPI v2.8.1
[21:58:49 INFO]: [TriggerReactor] Enabled support for Vault Vault v1.6.1
[21:58:49 INFO]: [TriggerReactor] Vault permission hooked.
[21:58:49 INFO]: [TriggerReactor] Vault chat hooked.
[21:58:49 INFO]: [TriggerReactor] Vault economy hooked.
[21:58:49 INFO]: [TriggerReactor] Enabled support for CoreProtect CoreProtect v2.12.0
[21:58:49 INFO]: [TriggerReactor] Enabled support for Factions Factions v1.6.9.5-U0.1.21
[21:58:49 ERROR]: Error occurred while enabling TriggerReactor v1.4.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/massivecraft/factions/entity/FactionColl
        at io.github.wysohn.triggerreactor.bukkit.manager.trigger.share.api.faction.FactionsSupport.init(FactionsSupport.java:61) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.core.manager.trigger.share.api.AbstractAPISupport.addSharedVar(AbstractAPISupport.java:60) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onEnable(JavaPluginBridge.java:240) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:58) ~[TriggerReactor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

`Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.entity.FactionColl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
        ... 15 more`

When I execute any trg commands:
`org.bukkit.command.CommandException: Unhandled exception executing command 'trg' in plugin TriggerReactor v1.4.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-db6de12-07c3001]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-07c3001]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-07c3001]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

`Caused by: java.lang.NullPointerException
        at io.github.wysohn.triggerreactor.core.main.TriggerReactor.onCommand(TriggerReactor.java:147) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onCommand(TriggerReactor.java:71) ~[TriggerReactor.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-db6de12-07c3001]
        ... 15 more`

**Comment by wysohn** [comment]
It's because I used the latest version of MassiveCore library or simply you don't have MassiveCore 

Do you have both MassiveCore and Factions?

I will fix this anyway though

**Comment by Ghost295** [comment]
FactionsUUID does not use MassiveCore so no I do not have MassiveCore on the server

**Comment by Ghost295** [comment]
Will it work without massivecore and with FactionUUID?

**Comment by wysohn** [comment]
It's just looking for com/massivecraft/factions/entity/FactionColl but couldn't find it

I'm not sure what factionUUID, but isn't it kind of add-on for the Factions?

In that case, Factions need MassiveCore if I remember it correctly

I just don't get how FactionsUUID plugin is causing FactionsSuppirt to load

It should not load unless TriggerReactor find the plugin actually exists.

It's loaded them a plugin named Faction should exist

If that's the case, MassiveCore is required for sure

I'm quite confused about your settings there

**Comment by Ghost295** [comment]
They both use the same name "Factions"  and since FactionUUID has nothing to do with massivecore it returns null?
And factionUUID is a standalone version of faction: It is not linked to massivecore
https://www.spigotmc.org/resources/factionsuuid.1035/

**Comment by wysohn** [comment]
Can't do much about it since the author somehow decided to use the same name for plugin

The third party plugin like TriggerReactor have no way to see if it's Factions or FactionsUUID except checking their name

Unfortunately, they share the same name; I have no way to fix it at my side

One fix can be just open up the FactionsUUID.jar file and change the plugin.yml in it

Change it to FactionsUUID or something instead of Factions

Then, FactionsSupport module will not load

**Comment by Ghost295** [comment]
Ok thanks, I will try that

**Comment by Ghost295** [comment]
Could you check for the author's name?

**Comment by wysohn** [comment]
No, the current support is aimed for the Factions plugin not FactionsUUID

If FactionsUUID was sort of fork version of Factions, it would work

But it seems the FactionsUUID is a whole new version of Factions

This means all the codes in it can differ a lot compared to actual Factions plugin

You still can access them using function plugin()

    theplugininstance = plugin("FactionsUUID")

But I'm not planning to add specific support for the FactionsUUID atm

**Comment by Ghost295** [comment]
A made a temporary fix, I modified your FactionsSupport Class to support FactionUUID's api, and now it works without changing the name of the plugin.
I guess to support it, you could add in the config whether or not to use FactionUUID's api or Factions since you can not detect which one the server is using.
