### ISSUE TITLE
illegal character in path

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#87]
[17:27:05 WARN]: java.net.URISyntaxException: Illegal character in path at index 31: file:///C:/Users/양채운/Desktop/서 버 파일/RL PvP/plugins/TriggerReactor.jar
[17:27:05 WARN]:        at java.net.URI$Parser.fail(Unknown Source)
[17:27:05 WARN]:        at java.net.URI$Parser.checkChars(Unknown Source)
[17:27:05 WARN]:        at java.net.URI$Parser.parseHierarchical(Unknown Source)
[17:27:05 WARN]:        at java.net.URI$Parser.parse(Unknown Source)
[17:27:05 WARN]:        at java.net.URI.<init>(Unknown Source)
[17:27:05 WARN]:        at io.github.wysohn.triggerreactor.tools.JarUtil.copyFolderFromJar(JarUtil.java:49)
[17:27:05 WARN]:        at io.github.wysohn.triggerreactor.tools.JarUtil.copyFolderFromJar(JarUtil.java:32)
[17:27:05 WARN]:        at io.github.wysohn.triggerreactor.bukkit.manager.ExecutorManager.<init>(ExecutorManager.java:50)
[17:27:05 WARN]:        at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onEnable(JavaPluginBridge.java:259)
[17:27:05 WARN]:        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:58)
[17:27:05 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[17:27:05 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
[17:27:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404)
[17:27:05 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386)
[17:27:05 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335)
[17:27:05 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
[17:27:05 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
[17:27:05 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
[17:27:05 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292)
[17:27:05 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[17:27:05 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:27:05 ERROR]: Error occurred while enabling TriggerReactor v2.1.0 (Is it up to date?)
java.lang.NullPointerException: null
        at java.io.FileInputStream.<init>(Unknown Source) ~[?:1.8.0_181]
        at io.github.wysohn.triggerreactor.tools.JarUtil.copyFolderFromJar(JarUtil.java:53) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.tools.JarUtil.copyFolderFromJar(JarUtil.java:32) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.manager.ExecutorManager.<init>(ExecutorManager.java:50) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onEnable(JavaPluginBridge.java:259) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onEnable(TriggerReactor.java:58) ~[TriggerReactor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1237]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
[17:27:05 INFO]: [TriggerReactor] Disabling TriggerReactor v2.1.0
[17:27:05 INFO]: [TriggerReactor] Finalizing the scheduled script executions...
[17:27:05 ERROR]: Error occurred while disabling TriggerReactor v2.1.0 (Is it up to date?)
java.lang.NullPointerException: null
        at io.github.wysohn.triggerreactor.bukkit.main.JavaPluginBridge.onDisable(JavaPluginBridge.java:352) ~[TriggerReactor.jar:?]
        at io.github.wysohn.triggerreactor.bukkit.main.TriggerReactor.onDisable(TriggerReactor.java:65) ~[TriggerReactor.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:386) [patched_1.12.2.jar:git-Paper-1237]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:335) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1237]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1237]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]

**Comment by wysohn** [comment]
[] can cause error still
