### ISSUE TITLE
AreaTrigger throws exception

### ISSUE THREAD

**Issue by wysohn** [wysohn/TriggerReactor#98]
[12:33:12 WARN]: Exception in thread "AreaTriggerManager -- EntityTrackingThread"
[12:33:12 WARN]: java.util.ConcurrentModificationException
[12:33:12 WARN]:        at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
[12:33:12 WARN]:        at java.util.ArrayList$Itr.next(Unknown Source)
[12:33:12 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getEntities(CraftWorld.java:621)
[12:33:12 WARN]:        at io.github.wysohn.triggerreactor.bukkit.manager.trigger.AreaTriggerManager$1.run(AreaTriggerManager.java:63)
[12:33:12 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by wysohn** [comment]
![image](https://user-images.githubusercontent.com/8789836/49977099-d47be000-fef9-11e8-91ee-9a71794b2d62.png)

**Comment by wysohn** [comment]
Probably already fixed
